# Generated by Django 5.1 on 2024-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMainWorkspace', '0002_folder_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='tag_name',
            field=models.CharField(default='Tag', max_length=100),
        ),
    ]
