# Generated by Django 5.1 on 2024-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMainWorkspace', '0006_alter_folder_folder_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
