# Generated by Django 5.0 on 2024-02-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='Tag', max_length=30)),
                ('tag_slug', models.SlugField(blank=True, max_length=200)),
                ('tag_count', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=30)),
                ('folder_slug', models.SlugField(blank=True, max_length=200)),
                ('folder_description', models.CharField(blank=True, default='', max_length=30)),
                ('created', models.DateField(auto_now_add=True)),
                ('folder_img', models.ImageField(blank=True, default='img/folder_img/folder-black.png', upload_to='img/folder_img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='userMainWor_created_365fe5_idx')],
            },
        ),
    ]
