# Generated by Django 5.0 on 2024-02-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMainWorkspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
