# Generated by Django 5.0 on 2024-02-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userMainWorkspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateUserNoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_img', models.FileField(blank=True, default='', upload_to='files/img/')),
                ('note_video', models.FileField(blank=True, default='', upload_to='files/video/')),
                ('note_audio', models.FileField(blank=True, default='', upload_to='files/audio/')),
                ('note_audio_title', models.TextField(blank=True, default='')),
                ('note_audio_author', models.TextField(blank=True, default='')),
                ('note_audio_image', models.TextField(blank=True, default='')),
                ('note_other', models.FileField(blank=True, default='', upload_to='files/other/')),
                ('note_other_size', models.IntegerField(blank=True, default=0)),
                ('note_folder', models.ManyToManyField(blank=True, to='userMainWorkspace.folder')),
                ('note_tag', models.ManyToManyField(blank=True, to='userMainWorkspace.usertag')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(default='Моя думка', max_length=50)),
                ('note_content', models.TextField(blank=True, default='')),
                ('note_file', models.JSONField(blank=True, default=dict)),
                ('note_slug', models.SlugField(blank=True, max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note_folder', models.ManyToManyField(blank=True, to='userMainWorkspace.folder')),
                ('note_tag', models.ManyToManyField(blank=True, to='userMainWorkspace.usertag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
