# Generated by Django 5.1 on 2024-08-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userNote', '0003_alter_usernote_note_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateusernotecontent',
            name='note_audio',
            field=models.FileField(blank=True, default='', max_length=999, upload_to='files/audio/'),
        ),
        migrations.AlterField(
            model_name='templateusernotecontent',
            name='note_audio_author',
            field=models.TextField(blank=True, default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='templateusernotecontent',
            name='note_audio_image',
            field=models.TextField(blank=True, default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='templateusernotecontent',
            name='note_audio_title',
            field=models.TextField(blank=True, default='', max_length=999),
        ),
    ]
