# Generated by Django 5.2.4 on 2025-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_event_description_event_location_event_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('url', models.URLField(max_length=255, unique=True)),
                ('status', models.CharField(default='New', max_length=6)),
            ],
        ),
    ]
