# Generated by Django 5.2.4 on 2025-08-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_ticket_deal_value_ticket_delivery_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
