# Generated by Django 5.2.4 on 2025-09-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_remove_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='New', max_length=6),
        ),
    ]
