# Generated by Django 5.2.4 on 2025-09-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
