# Generated by Django 5.2.4 on 2025-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_rename_description_event_date_remove_event_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='New', max_length=9),
        ),
    ]
